baseurl = "https://halfwitprogrammer.com"
languageCode = "en-us"
title = "Halfwit Programmer"
theme = "mainroad"
disqusShortname = "halfwitprogrammer"
paginate= 10

GoogleAnalytics = "UA-122297209-1"

[params]
  author = "Terrence Drumm"
  subtitle = "My adventure to build something useful"
  opengraph = true
  twitter_cards = true
  readmore = true
  authorbox = true
  

[Author] # Used in authorbox
  name = "Terrence Drumm"
  bio = "I'm a self learned developer and I just love building things"
  

[taxonomies]
    tag = "tags"
    category = "categories"
    

[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/page/about/"
    weight = -110

[[menu.main]]
    name = "Agile Reaction"
    weight = 100
    url = "https://www.agilereaction.com/"

[[menu.main]]
    name = "Gitlab"
    weight = 20
    url = "https://gitlab.com/TDog"

[[menu.main]]
    name = "Twitter"
    weight = 20
    url = "https://twitter.com/TDogVoid"

[[menu.main]]
    name = "Create a Twitch Bot"
    weight = 10
    url = "http://skl.sh/2eyhlh2"

[related]

    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 80

    # Will lower case keywords in both queries and in the indexes.
    toLower = true

    [[related.indices]]
        name = "keywords"
        weight = 150
    [[related.indices]]
        name  = "author"
        toLower = true
        weight = 30
    [[related.indices]]
        name  = "tags"
        weight = 100
    [[related.indices]]
        name  = "date"
        weight = 10
        pattern = "2006"