baseurl = "http://halfwitprogrammer.com"
languageCode = "en-us"
title = "Halfwit Programmer"
theme = "halfwit-theme"
disqusShortname = "halfwitprogrammer"

[params]
    author = "Terrence Drumm"
    headerColor = "green accent-4"
    footerColor = "green accent-4"
