baseurl = "https://halfwitprogrammer.com"
languageCode = "en-us"
title = "Halfwit Programmer"
theme = "mainroad"
disqusShortname = "halfwitprogrammer"
paginate= 10

GoogleAnalytics = "UA-122297209-1"

[params]
  author = "Terrence Drumm"
  subtitle = "My adventure to build something useful"
  opengraph = true
  twitter_cards = true
  readmore = true
  authorbox = true


[Author] # Used in authorbox
  name = "Terrence Drumm"
  bio = "I'm a self learned developer and I just love building things"
  

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "TDogVoid"
  github = "TDogVoid"
  gitlab = "TDog"

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[taxonomies]
    tag = "tags"
    category = "categories"
    

[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/page/about/"
    weight = -110

[[menu.main]]
    name = "Agile Reaction"
    weight = 100
    url = "https://www.agilereaction.com/"


[[menu.main]]
    name = "Create a Twitch Bot"
    weight = 10
    url = "http://skl.sh/2eyhlh2"

[related]

    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 80

    # Will lower case keywords in both queries and in the indexes.
    toLower = true

    [[related.indices]]
        name = "keywords"
        weight = 150
    [[related.indices]]
        name  = "author"
        toLower = true
        weight = 30
    [[related.indices]]
        name  = "tags"
        weight = 100
    [[related.indices]]
        name  = "date"
        weight = 10
        pattern = "2006"