baseurl = "http://halfwitprogrammer.com"
languageCode = "en-us"
title = "Halfwit Programmer"
theme = "halfwit-theme"
disqusShortname = "halfwitprogrammer"
paginate= 10

[params]
    author = "Terrence Drumm"
    headerColor = "green accent-4"
    footerColor = "green accent-4"

[taxonomies]
    tag = "tags"
    category = "categories"
    

[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/page/about/"
    weight = -110

[[menu.main]]
    name = "Tags"
    weight = 3
    identifier = "tags"
    url = "/tags/"